spring.application.name=ws_project_weather_web_service
spring.datasource.url=jdbc:postgresql://localhost:5432/ws-project
spring.datasource.username=postgres
spring.datasource.password=Eiserman93
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update

# Api keys
geocode.api.key=66ec15307c9a0191546411hdz9e4ea4

# Https and ssl
server.ssl.key-store=/app/resources/mykeystore.p12
server.ssl.key-store-password=Eiserman93
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=mycert
server.port=8443
server.http.redirect-to-https=true

